### ISSUE TITLE
Graphs are not shown (blank page with 5 buttons only)

### ISSUE THREAD

**Issue by edumerco** [org-roam/org-roam-server#12]
1. I installed the package from MELPA as per the instructions, without visible problems.  
2. started the server, without seeing any special notice. 
3. When I open http://127.0.0.1:8080/, I see only 1 button in the top-left (enable preview), 3 in the top-right (database network, buffer network, file viewer) and 1 at bottom-right (reload, in red), but nothing is showing in the central space (see attached screen capture). 
![RoamServer-WhitePage](https://user-images.githubusercontent.com/1304807/82350170-616d7780-99d1-11ea-987f-211941c4443f.png)

When "File viewer" is pressed, 2 rectangles appear and in the top-left a combobox appears, but without any options. Near it, top-left from the left rectangle, a blue "Back" appears. 
 
I'm in Debian 10 with i3, and tested with Firefox 68.8.0esr and Google Chrome 81.0.4044.138 (Build oficial), with the same result. 

How can I help to debug this issue? Any more info, or some specific test? 
I'm not very knowledgeable on code or development, but can follow instructions. :)

Thanks a lot...

**Comment by goktug97** [comment]
Can you open up your browser's console and see if there is an error that might be indicating what is happening

**Comment by edumerco** [comment]
Thanks! I learned something new, it's the 1st time I do this. :)

Yes, 2 errors appear: 
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8080/assets/vis-network.min.js
Source Map URL: vis-network.min.js.map

Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8080/assets/bootstrap.min.js
Source Map URL: bootstrap.min.js.map

Searching in my disk, I found those 2 files in 
/home/edumerco/.emacs.d/elpa/org-roam-server-20200516.1538/assets (~770 and 48 Kb), which seems the right place. Looks like the server is not finding them somehow?

**Comment by goktug97** [comment]
Source maps (min.js.map) are for debugging and I've never used them myself but they are not required for program to work. I get those errors too. I know it sounds silly but can you close and open emacs and try again if you haven't done it before. If that doesn't work, can you also try installing from the source to see if it makes any difference.

```elisp
(use-package org-roam-server
  :ensure nil
  :load-path "~/org-roam-graph-server/")
```

**Comment by edumerco** [comment]
Re-booted emacs> same error. 
Installed from source> same error. 

Trying to see more, opened the web console (in Firefox) and upon clicking...

- reload > TypeError: roamSource is undefined127.0.0.1:8080:234:15
- other buttons > nothing. 

Does that help? What else can I do to find more info? :)

**Comment by goktug97** [comment]
I think you pressed reload button and as `roamSource` is not initialized you got that error. It seems connection to the roam-data hasn't been established. Can you open http://127.0.0.1:8080/roam-data?force=1 and see if `download` pops up.

**Comment by edumerco** [comment]
going to force=1throws: 

> 500 Internal Error
> Internal error when handling this request.
> error: (emacsql-error no such column: refs.type)

BTW, thanks a lot for your work... :)

**Comment by goktug97** [comment]
> BTW, thanks a lot for your work... :)

Appreciate that!

The database structure is changed in org-roam v1.1.1. `type` is added to the `refs` table (https://github.com/org-roam/org-roam/pull/547). Updating the `org-roam` and rebuilding the cache should fix this issue.

**Comment by edumerco** [comment]
It worked! It was that, I had a previous version.
Thanks a lot... :D 

I can't find nothing as org-roam-version, but for a newbie like me, that may help to troubleshoot these things (like org-version or emacs-version). Does that make sense, or it's just my ignorance? 

Again, thanks a lot for your kind help. :smiley:

**Comment by goktug97** [comment]
Awesome!!

Yeah, that makes sense.

**Comment by jethrokuan** [comment]
@goktug97 we have `org-roam-diagnostics` now (h.t. @progfolio), for me, it prints:

```
- Emacs: GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.14, cairo version 1.17.3)
 of 2020-04-03
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/jethro/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.1.1
```

**Comment by edumerco** [comment]
Great! 

For me (just for the records and learning if someone else finds this in the future) after asking framework (N/A in my case, since it's vanilla emacs slowly customized) prints: 

- Emacs: GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.5)
 of 2019-09-23, modified by Debian
- Framework: N/A
- Org: Org mode version 9.3.6 (9.3.6-25-g685b2c-elpa @ /home/edumerco/.emacs.d/elpa/org-20200330/)
- Org-roam: 1.1.1

Thanks again! :smile:

**Comment by lyq0930** [comment]
Hi, I'm having the same issue here. The only difference is I do get `Connection to /roam-data: success`, and all notes are showing but there is no links among notes. Here is what I got from console.

 ```
Uncaught Error: Unknown dataType
    at e.value (VM268 vis-network.min.js:85)
    at updateNodesAndEdges ((index):548)
    at update ((index):383)
    at Object.success ((index):362)
    at c (VM267 jquery-3.5.0.min.js:2)
    at Object.fireWith [as resolveWith] (VM267 jquery-3.5.0.min.js:2)
    at l (VM267 jquery-3.5.0.min.js:2)
    at XMLHttpRequest.<anonymous> (VM267 jquery-3.5.0.min.js:2)
```

```
Copy info below this line into issue:
- Emacs: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0, NS appkit-1894.40 Version 10.15.4 (Build 19E287))
 of 2020-05-08
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /Users/louie/.config/emacs/.local/straight/build/org-mode/)
- Org-roam: 1.1.1
```

**Comment by goktug97** [comment]
I only get this error when there is no connection between notes. Does `org-roam-graph` produce expected result?

**Comment by wayanjimmy** [comment]
@lyq0930 having the same issue. fortunately, I fixed by removing extra slash on the end of my org-roam-directory path

```diff
(setq
- org_notes "~/Labs/zettlr/"
+ org_notes "~/Labs/zettlr"
 org-directory org_notes
 org-roam-directory org_notes)
```

**Comment by bmgxyz** [comment]
I'm seeing this issue as well, but none of the solutions in this thread so far have worked for me.

Here's my setup:

```M-x org-roam-diagnostics RET```:
```
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw scroll bars)
 of 2020-10-27
- Framework: Doom
- Org: Org mode version 9.4 (nil @ /home/<user>/.emacs.d/.local/straight/build/org-mode/)
- Org-roam: 1.2.2
```

```config.el```:
```
(setq org-directory "~/org/")
...
(setq org-roam-directory "~/org/roam")
...
(use-package org-roam-server
  :ensure t
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-label-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20))
```

```packages.el```:
```
...
(package! org-roam-server)
...
```

When I go to http://127.0.0.1:8080/, I see this warning in the console:

```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental
effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
```

which seems harmless enough. I've also seen the `bootstrap.min.js` issue, but I can't reproduce it reliably.

When I go to http://127.0.0.1:8080/roam-data?force=1, I see this error:

```
error: (emacsql-error near line 183: no such column: dest)
```

Any ideas? I'm not that new to Emacs, but I am new to Doom and Org-roam, so I welcome any suggestions.

In any case, **thank you** for making this software. It looks useful, and I'm excited to start using it.

**Comment by goktug97** [comment]
Update `org-roam`

https://github.com/org-roam/org-roam-server/pull/104

**Comment by tea4or2wo** [comment]
Same problem here, suggestions mentioned above did not work so far.

My setup:

```
- Emacs: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.18.9)
 of 2019-09-05
- Framework: N/A
- Org: Org mode version 9.4 (9.4-elpa @ /home/.emacs.d/elpa/org-9.4/)
- Org-roam: 1.2.3
```

When visiting  [http://127.0.0.1:8080/](http://127.0.0.1:8080/), I get this error in the console:

```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

When visiting [http://127.0.0.1:8080/roam-data?force=1](http://127.0.0.1:8080/roam-data?force=1), I get this error:

```
500 Internal Error

Internal error when handling this request.

error: (emacsql-error near line 35: no such column: links.to)
```

Any help appreciated.

**Comment by tea4or2wo** [comment]
`org-roam-server` was not up to date, problem solved with `20201025.1434`.

See #55, #57 and #69.

Sorry for the noise.

**Comment by m4xxed** [comment]
Hey guys, this issue still persists for me. 

I have tried everything in this issue thread. Everything is up to date, I quadruple-checked.
What I experience on both firefox and chromium is that the site loads, then the nodes and connections blink once (ordered in a circle still) and then they vanish and do not come back. In Buffer Network View, I can select my files in the buffer. 

My org-roam-diagnostics output:

```
- Emacs: GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3)
 of 2020-08-28
- Framework: N/A
- Org: Org mode version 9.4.4 (9.4.4-4-g99eafe-elpaplus @ /home/<username>/.config/emacs.packages/org-plus-contrib-20210104/)
- Org-roam: 1.2.3
```

Firefox console reports those errors & warnings:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/

Uncaught Error: undefinedvis-network.min.js:85:256520
value http://127.0.0.1:8080/assets/vis-network.min.js:85

Connection to /roam-data: success

Source map error: Error: request failed with status 404
Resource URL: http://127.0.0.1:8080/assets/vis-network.min.js
Source Map URL: vis-network.min.js.map
```

I have cleared and rebuild the database-file multiple times, I have restarted emacs multiple times. Creating graphs with org-roam-graph works fine. 

Please help, I love the server-feature :)
