### ISSUE TITLE
Org-roam-server may change the export of inline images

### ISSUE THREAD

**Issue by Iorest** [org-roam/org-roam-server#26]
Hello,Thanks for this awesome project.

But,I encountered a problem when I using org-roam, that is, the picture will not be exported. I am very puzzled. I checked for a long time, until I closed the org-roam-server-mode, everything works well again, I guess there may be some problems.

Can anyone help me?

**Comment by goktug97** [comment]
https://github.com/org-roam/org-roam-server/commit/b06828e1e6f12f1d22c6f91e0570089214add819 Fixed it.

It should work now.

**Comment by Iorest** [comment]
Yes, It works when I export a html file.
But, when I export other files ,like a latex file,this problem still appears.

**Comment by goktug97** [comment]
https://github.com/org-roam/org-roam-server/commit/99b56ceadc4bc59bd976b3c9f49c3dc2aeb60d36
Hopefully, it is fixed now.

**Comment by goktug97** [comment]
Can you close the issue if it is resolved.

**Comment by Iorest** [comment]
Yes,it solves my problem
